### PR TITLE
fix PR190

### PR DESCRIPTION
**Pull request by Piranias**
Fix #190

**Changes proposed in this pull request**:
- adding some comments that were not solved in PR #190
- added two weather data sets for 2017 for madrid and berlin with new dhi calculation method.

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [x] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by MaGering** [comment]
@Piranias, I would like to use this PR for also adding `run_pv_compare_example_sector_coupling.py`

**Comment by Piranias** [comment]
> @Piranias, I would like to use this PR for also adding `run_pv_compare_example_sector_coupling.py`

ok, sure! Go ahead :)

**Review by MaGering — APPROVED** [review]
Besides these two little things in my comments below, I found, while creating `run_pv_compare_example_sector_coupling.py`, that line 19 of `run_pv_compare_example_electricity_sector.py` should look like this:

```
outputs_directory = os.path.join(constants.EXAMPLE_OUTPUTS_DIRECTORY, scenario_name)
```

I'll change it and ask you for a review @Piranias  :)

**Comment by Piranias** [comment]
> Besides these two little things in my comments below, I found, while creating `run_pv_compare_example_sector_coupling.py`, that line 19 of `run_pv_compare_example_electricity_sector.py` should look like this:
> 
> ```
> outputs_directory = os.path.join(constants.EXAMPLE_OUTPUTS_DIRECTORY, scenario_name)
> ```
> 
> I'll change it. It would be great if you could review my changes then @Piranias :)

are you still going to change this?

**Review by MaGering — APPROVED** [review]
Thank you for adding the correct data and adapting the demand calculations! :)

I could validate the calculated electricity and heat demands using [Umweltbundesamt](https://www.umweltbundesamt.de/daten/private-haushalte-konsum/wohnen/energieverbrauch-privater-haushalte#endenergieverbrauch-der-privaten-haushalte) as reference.

- 126.5771 TWh is the electricity demand in Germany in 2018 and is approximately what you can read in figure 1 in the reference. 
- For a population of 48000 people in our example we get a `Total_demandElectricity` in `scalars.xlsx` of 60368679.2362247 kWh. Dividing it by population and multiplying with Germanys population in 2017 (82521653) leads to a electricity demand of 103.79 TWh. This is the same value I've calculated using the raw data. So the calculations in demand.py work as intended. :)
- 405.0878 TWh is the heat demand for space heating in Germany in 2018 and is a little lower than in figure 2 of [Umweltbundesamt]. The hot water demand on the other hand is 
with 119.9872 TWh a little higher than in figure 2.
- I validated the calculations of the heat demand in the same way as done with the electricity demand and got 412.8 TWh, which is approximately the same as the value of 2017 in the raw data.

**Pull request merged**
