### PR TITLE
Function: add_local_grid_parameters()

### LINKED ISSUE #209: [Data] Electricity prices, feed-in tariffs, gas prices
I've delegated #208 and #194, research about feed-in tariff and gas prices.

We could also update the electricity prices, year 2020 is available here now: https://ec.europa.eu/eurostat/databrowser/view/ten00117/default/table?lang=en

This brought me to the question: how would you like the data to be structured?

1. separate csvs for gas prices, electricity prices, feed-in tariffs 
2. one csv with columns "gas_price", etc.. (only for one year, preferably 2020 or 2019)

### PR DESCRIPTION
**Pull request by Piranias**
Fix #209 #208 #194

**Changes proposed in this pull request**:
- add_local_grid_parameters() that fills in electricity price, feed-in tariff, CO2 emissions,
    renewable share, gas price automatically
- gas price is only filled in if column "Gas plant" exists in energyProviders.csv

The following steps were realized, as well (if applies):
- [x] Use in-line comments to explain your code
- [x] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [x] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [x] Apply black (`black . --exclude docs/`)
- [x] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Review by MaGering — CHANGES_REQUESTED** [review]
Should we maybe set the energy prices and tariffs to zero in our example's data (`energyProviders.csv`)? This would guarantee that we obtain the correct values in the simulations, plus we wouldn't need to adapt it twice if we'd find a mistake in that value later on.

**Comment by Piranias** [comment]
> Should we maybe set the energy prices and tariffs to zero in our example's data (`energyProviders.csv`)? This would guarantee that we obtain the correct values in the simulations, plus we wouldn't need to adapt it twice if we'd find a mistake in that value later on.

I'm not sure what you mean with that "This would guarantee that we obtain the correct values in the simulations"?

The values are collected from the excel sheet in static_inputs, so we only need to adapt these values if we find that something is not correct..

**Comment by MaGering** [comment]
> > Should we maybe set the energy prices and tariffs to zero in our example's data (`energyProviders.csv`)? This would guarantee that we obtain the correct values in the simulations, plus we wouldn't need to adapt it twice if we'd find a mistake in that value later on.
> 
> I'm not sure what you mean with that "This would guarantee that we obtain the correct values in the simulations"?
>
> The values are collected from the excel sheet in static_inputs, so we only need to adapt these values if we find that something is not correct..

Sorry, my bad. I didn't realize we have `overwrite_grid_parameters=True` in our examples. For the `energy_price` of the `Gas plant` however this seems not to work... Do you know why the old value there is not overwritten?

**Comment by Piranias** [comment]
> > > Should we maybe set the energy prices and tariffs to zero in our example's data (`energyProviders.csv`)? This would guarantee that we obtain the correct values in the simulations, plus we wouldn't need to adapt it twice if we'd find a mistake in that value later on.
> > 
> > 
> > I'm not sure what you mean with that "This would guarantee that we obtain the correct values in the simulations"?
> > The values are collected from the excel sheet in static_inputs, so we only need to adapt these values if we find that something is not correct..
> 
> Sorry, my bad. I didn't realize we have `overwrite_grid_parameters=True` in our examples. For the `energy_price` of the `Gas plant` however this seems not to work... Do you know why the old value there is not overwritten?

so in my examples it is overwritten. I fixed the examples overwrite option, let me know if everything works now.

**Comment by MaGering** [comment]
> > > > Should we maybe set the energy prices and tariffs to zero in our example's data (`energyProviders.csv`)? This would guarantee that we obtain the correct values in the simulations, plus we wouldn't need to adapt it twice if we'd find a mistake in that value later on.
> > > 
> > > 
> > > I'm not sure what you mean with that "This would guarantee that we obtain the correct values in the simulations"?
> > > The values are collected from the excel sheet in static_inputs, so we only need to adapt these values if we find that something is not correct..
> > 
> > 
> > Sorry, my bad. I didn't realize we have `overwrite_grid_parameters=True` in our examples. For the `energy_price` of the `Gas plant` however this seems not to work... Do you know why the old value there is not overwritten?
> 
> so in my examples it is overwritten. I fixed the examples overwrite option, let me know if everything works now.

Yes, my bad. It works. Thank you for checking. :)

**Review by MaGering — APPROVED** [review]

**Pull request merged**
