### PR TITLE
Fix/hp cop below zero

### PR DESCRIPTION
**Pull request by MaGering**
Fix Issue https://github.com/greco-project/pvcompare/issues/60 and https://github.com/greco-project/pvcompare/issues/111

With this PR problems observed during the calculation of the heat pump's power are fixed.

COPs/EERs that are below zero will be set to `np.inf`. They result from temp_low > temp_high and will therefore be represented with COP/EER -> infinity.

This equation

cop_equation

shows that a `COP` approaching infinity results from an electrical power `P_el` approaching zero or vice versa.

Currently COP/EER below zero are set to 0. At ambient temperatures below `temp_high` this condition is not fulfilled and the simulation runs through without errors. However, if the ambient temperature exceeds `temp_high`, we get a `ZeroDevision Error` when calculating the electrical power `P_el` from the `COP` and the useful heat flow `Q_useful`.

Setting the COP towards 0 leads to a electrical power `P_el` towards infinity, which is not representative for summer periods (ambient temperature > `temp_high`) as shown in this figure:
Electricity bus_power

Setting the COP towards infinity however leads to a simulation of the heat pump with the expected behavior in summer:
Electricity bus_power

The following steps were realized, as well (if applies):
- [x] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [x] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by MaGering** [comment]
I'm going to write a test(s) on a separate branch while solving issue https://github.com/greco-project/pvcompare/issues/66

**Review by c-moeller — APPROVED** [review]
Great :+1:

**Comment by MaGering** [comment]
@SabineHaas it's ready for review now if you like to. :)

**Review by SabineHaas — APPROVED** [review]
Nice! Thank you for explaining so well :)

**Pull request merged**
