### PR TITLE
update check_energy_price function to automatically determine the grid-sourced electricity price and add tests

### PR DESCRIPTION
**Pull request by mahendrark**
This PR is a continuation of #30

### CODE REVIEW

**Comment by mahendrark** [comment]
@SabineHaas 

I had a call with PF yesterday and he suggested that I do not work with the other branches and he told me to create a new branch and helped me get the latest commits from the branch `read_energy_price` into this branch. 

I created the setup_method, hardcoded the NaN value into a DF and then to CSV, preparing it for the tests. 
Both the tests work now without any problem for me locally.

**Comment by Piranias** [comment]
Hi @mahendrark,
I just started to check the brach "fix/energy_price". I found that the csv file "electricity_prices_households.csv" is missing in the input folder. can you add it to the branch?
also, you are done with all your changes, right?

**Comment by Piranias** [comment]
> Hi @mahendrark,
> I just started to check the brach "fix/energy_price". I found that the csv file "electricity_prices_households.csv" is missing in the input folder. can you add it to the branch?
> also, you are done with all your changes, right?

nevermind, I fixed it already

**Comment by mahendrark** [comment]
@Piranias 

yep, done with the changes. 
you can review and merge it

**Comment by Piranias** [comment]
Hi, 
I have implemented some changes to the function, the tests and added everything to the main module. What it does now is the following:

- the option to enter an energy_price in the main function is deleted. I don't see why especially the energy_price should be added manually and we cannot provide this option for all parameters, it would be an endless list. The user can just enter it into the csv like all the other parameters.
- the function add_electricity_price is called and checks if there is a value provided in energyProviders. If there is a value (unequal None), and it differs from the reference value in the energy_price.csv a warning is given, but the value is not overwritten automatically. The warning informs that the value should be set to None if the user wants to add the electricity_price automatically.
- only if the value in energyProviders.csv is None, the electricity price is added automatically. 

FAILING CHECKS:
The checks show some error in the setup.py and the requirements. This probably has to do with the updated mvs. @SabineHaas can you quickly take a look at the failing build and tell me if you can solve this easily?

**Comment by SabineHaas** [comment]
> The checks show some error in the setup.py and the requirements. This probably has to do with the updated mvs. @SabineHaas can you quickly take a look at the failing build and tell me if you can solve this easily?

The requirements.txt was changed 6 days ago but the oemof version has not been changed since 10 months ago -- [see here](https://github.com/rl-institut/mvs_eland/blame/dev/requirements.txt). I think I need to take a bit more time to look into this. When trying to install the current dev of MVS locally I get similar errors but with other packages. When using dev  @ `aa59f7de703b5517b49df82a4ed6aa13f3ee6aca` I don't get any error.

**Pull request merged**
