### PR TITLE
Trigger builds on push for dev and master and for every PR

### LINKED ISSUE #215: Get build for dev branch with github actions
Currently there's no build for dev branch in our CI. 
Will fix this to: 
Build on push events to dev and master branch, build on each pull request

### PR DESCRIPTION
**Pull request by SabineHaas**
Fix #215

**Changes proposed in this pull request**:
- Trigger builds on push events for dev and master branches and for every PR

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by SabineHaas** [comment]
@Piranias I'm not 100 % sure whether this is the right setting for push and pull_request, but it's a try to automatically trigger builds for dev branch.

**Comment by Piranias** [comment]
hmm I'm not sure if I understand why we need this. Can't we just forbid pushes to dev and master branch?

**Comment by SabineHaas** [comment]
No this is about the build - I'm not sure whether it fixes that, but there's no build of dev branch in the CI now. Whenever a PR is merged into dev branch a build should be triggered.

**Comment by Piranias** [comment]
ok, I don't know either. but let's try it out.

**Review by Piranias — APPROVED** [review]

**Comment by SabineHaas** [comment]
Yes, build is triggered :)

**Pull request merged**
