### PR TITLE
Update/csvs is

### LINKED ISSUE #211: Update pvcompare to MVS v0.5.5
As soon as MVS is released to v0.5.5 we need to update pvcompare.

New features (not exhaustive):
- Stratified thermal energy storage (TES) MVS 
- Constraint: Minimal degree of autonomy [MVS #726](https://github.com/rl-institut/multi-vector-simulator/pull/726)
- xlrd requirement fixed in MVS #716
- KPI: degree of NZE 
- Constraint: net zero energy [[MVS #796](https://github.com/rl-institut/multi-vector-simulator/pull/796/)]
- `fixcost.csv` can be used now [MVS #795]

Changes:
- Precision limit of results set to 10e 6 [see PR](https://github.com/rl-institut/multi-vector-simulator/pull/791)
**Definition of Degree of Autonomy has changed**
Before: `DoA = generation / demand`, now: `DoA = (demand - consumption from provider) / demand` see [MVS commit](https://github.com/rl-institut/multi-vector-simulator/pull/726/commits/48f1ea11904020930ce78c8ca25b94754999dfb9)

Adaptions to be done:
- [x] Adapt all csvs: add minimal degree of autonomy to `constraints.csv` 
- [x] Adapt pvcompare to TES, done in #148 @MaGering is there anything else to adapt or will all adaptions  be covered in #148?
- [x] Remove `xlrd` from pvcompare requirements
- [x] Check for additional parameters and remove deprecated parameters in csvs. e.g. via [test inputs MVS](https://github.com/rl-institut/multi-vector-simulator/tree/dev/tests/inputs)
- [x] Adapt requirements: fix MVS version to the new release

### PR DESCRIPTION
**Pull request by Piranias**
Fix #211, #92

**Changes proposed in this pull request**:
- update MVS parameters for update to MVS v0.5.5
- Remove xlrd from pvcompare requirements
- Adapt MVS version to 0.5.5 
- Remove requirements.txt - now all requirements are in setup.py
- Adapted installation guide in README and gettingstarted
- Fixed link in README 

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by SabineHaas** [comment]
Thank you @Piranias! I'll use this PR to fix remaining tasks in #211.

**Comment by SabineHaas** [comment]
I've tested to install the requirements in a new virtual environment which worked fine for python 3.7 but not for python 3.8 (looong list of errors).
The checks have passed for both python versions though.

I started all examples - they run fine - did not wait for the optimization to finish, as it takes very long (is this the same for you?). 
I adapted fixcost.csv in the examples (copied from tests folder) and realized that not all values are set to 0 and if I set all values to 0 in fixcost.csv I get a ZeroDivisionError - just for your information.

@Piranias I cannot add you as reviewer as you have started the PR. 
It would be good if both of you check the installation and usage first before merging the PR. 
Probably it's better if you do it in a new environment and keep your old one to be save in case you have problems.

**Review by MaGering — CHANGES_REQUESTED** [review]
**Remove parameters in:**

1. [x] pvcompare/examples/example_user_inputs/mvs_inputs_electricity_sector/csv_elements/fixcost.csv
2. [x] pvcompare/examples/example_user_inputs/mvs_inputs_sector_coupling/csv_elements/fixcost.csv
3. [x] pvcompare/examples/example_user_inputs/mvs_inputs_sector_coupling_gas/csv_elements/fixcost.csv
4. [ ] pvcompare/tests/data/user_inputs/mvs_inputs/csv_elements/fixcost.csv

- `label`
- `dispatch_price`

**Add parameters in:**

5. [ ] pvcompare/tests/data_test_main/user_inputs/mvs_inputs/csv_elements/project_data.csv

- `scenario_description`

**`project_data.csv` missing in directory:**

6. [ ] pvcompare/tests/data/user_inputs_collection/mvs_inputs/csv_elements

**Comment by MaGering** [comment]
> I've tested to install the requirements in a new virtual environment which worked fine for python 3.7 but not for python 3.8 (looong list of errors).


> 
> I started all examples - they run fine - did not wait for the optimization to finish, as it takes very long (is this the same for you?).

It takes way longer! I waited for 20 min and stopped the simulation since it has never taken so long. What can be the problem? :-/


> It would be good if both of you check the installation and usage first before merging the PR.
> Probably it's better if you do it in a new environment and keep your old one to be save in case you have problems.


- With a new environment using python 3.7 I still have trouble installing from -e flag with these two packages:

   - psycopg2
   - graphiz

    I need to install them both with conda because pip install does not work for me. graphiz however is more of a mvs problem, since it is part of the installation there.

- With a new environment using python 3.8 I didn't get the psycopg2 error but also have some other error processing the demands.

My system info:

- Operating System: Ubuntu 20.04.2 LTS
- Kernel: Linux 5.4.0-66-generic
- Architecture: x86-64

**Comment by SabineHaas** [comment]
> > I've tested to install the requirements in a new virtual environment which worked fine for python 3.7 but not for python 3.8 (looong list of errors).
> 
> > I started all examples - they run fine - did not wait for the optimization to finish, as it takes very long (is this the same for you?).
> 
> It takes way longer! I waited for 20 min and stopped the simulation since it has never taken so long. What can be the problem? :-/
> 

Weird.. I've just run a simulation in MVS: fast as ever.. actually even faster after I pulled the current `dev`.

I also used `/pvcompare/examples/example_outputs/Scenario_example_sector_coupling/mvs_outputs/inputs/` as input folder directly with MVS current dev: duration of whole run ~ 1 minute (code in dev hasn't changed since the release). But same simulation takes ages when started with pvcompare in my new env. 
--> So, it must be something about the installed packages, I guess.. 

add. info:
Seems like it takes ages to create the oemof model `2021-03-11 16:16:38,251 - DEBUG - D0_modelling_and_optimization - Creating oemof model based on created components and busses...` the log file is too big to add it here :D

> > It would be good if both of you check the installation and usage first before merging the PR.
> > Probably it's better if you do it in a new environment and keep your old one to be save in case you have problems.
> 
>     * With a new environment using python 3.7 I still have trouble installing from -e flag with these two packages:
>       
>       * psycopg2
>       * graphiz
>       
>       I need to install them both with conda because pip install does not work for me. graphiz however is more of a mvs problem, since it is part of the installation there.
> 

Could you add a troubleshooting page in RTD and give this information? Just very short so that we document that it's a known problem. It's not urgent --> you could also just write an issue as reminder for later.

>     * With a new environment using python 3.8 I didn't get the psycopg2 error but also have some other error processing the demands.
> 
> 
> My system info:
> 
>     * Operating System: Ubuntu 20.04.2 LTS
> 
>     * Kernel: Linux 5.4.0-66-generic
> 
>     * Architecture: x86-64

**Comment by MaGering** [comment]
> Could you add a troubleshooting page in RTD and give this information? Just very short so that we document that it's a known problem. It's not urgent --> you could also just write an issue as reminder for later.

Sure! Should I do it though in rtd (`basic_usage.rst`) or in the `README.rst` under `Installation`?

**Comment by SabineHaas** [comment]
> > Could you add a troubleshooting page in RTD and give this information? Just very short so that we document that it's a known problem. It's not urgent --> you could also just write an issue as reminder for later.
> 
> Sure! Should I do it though in rtd (`basic_usage.rst`) or in the `README.rst` under `Installation`?

I think it fits well under `Installation`. I would also be fine with a separate section troubleshooting, e.g. as last page after `code documentation`, this way there's only one place, cause in case you add it under `Installation`you need to add it to `getting_started` and  `README`.

**Comment by MaGering** [comment]
> > > Could you add a troubleshooting page in RTD and give this information? Just very short so that we document that it's a known problem. It's not urgent --> you could also just write an issue as reminder for later.
> > 
> > 
> > Sure! Should I do it though in rtd (`basic_usage.rst`) or in the `README.rst` under `Installation`?
> 
> I think it fits well under `Installation`. I would also be fine with a separate section troubleshooting, e.g. as last page after `code documentation`, this way there's only one place, cause in case you add it under `Installation`you need to add it to `getting_started` and `README`.

Ok! I've added a section troubleshooting with commit https://github.com/greco-project/pvcompare/pull/251/commits/9b1a0434987db85b48dfd67b9c24de6e3d9a9f6d. Please let me know if there is something missing or not clear enough.

**Comment by SabineHaas** [comment]
> > > > Could you add a troubleshooting page in RTD and give this information? Just very short so that we document that it's a known problem. It's not urgent --> you could also just write an issue as reminder for later.
> > > 
> > > 
> > > Sure! Should I do it though in rtd (`basic_usage.rst`) or in the `README.rst` under `Installation`?
> > 
> > 
> > I think it fits well under `Installation`. I would also be fine with a separate section troubleshooting, e.g. as last page after `code documentation`, this way there's only one place, cause in case you add it under `Installation`you need to add it to `getting_started` and `README`.
> 
> Ok! I've added a section troubleshooting with commit [9b1a043](https://github.com/greco-project/pvcompare/commit/9b1a0434987db85b48dfd67b9c24de6e3d9a9f6d). Please let me know if there is something missing or not clear enough.

Looks perfect! Could you add the page to `index.rst` so that is appears in RTD? thanks a lot!

**Comment by SabineHaas** [comment]
Coming closer to the solution..

I used a clean environment and installed MVS. (without pvcompare, just `pip install multi_vector_simulator`)
→ simulation with mvs `tests/inputs` runs fine
→ simulation with pcompare `mvs_inputs_electricity_sector` : I stopped after 7 minutes
→ I checked the new and old versions of the packages and tried a few combinations: the simulation with `mvs_inputs_electricity_sector` as input runs fine with Pyomo 5.7.1 and 5.7.2 but not 5.7.3!!

We could require Pyomo 5.7.2 as a fast fix.

**Comment by MaGering** [comment]
> Coming closer to the solution..
> 
> I used a clean environment and installed MVS. (without pvcompare, just `pip install multi_vector_simulator`)
> → simulation with mvs `tests/inputs` runs fine
> → simulation with pcompare `mvs_inputs_electricity_sector` : I stopped after 7 minutes
> → I checked the new and old versions of the packages and tried a few combinations: the simulation with `mvs_inputs_electricity_sector` as input runs fine with Pyomo 5.7.1 and 5.7.2 but not 5.7.3!!
> 
> We could require Pyomo 5.7.2 as a fast fix.
> 
> This is the input folder I used (`mvs_inputs_electricity_sector`): [inputs.zip](https://github.com/greco-project/pvcompare/files/6130999/inputs.zip)

So cool @SabineHaas! I tested it for the sector coupling examples (heat pump with TES and gas) and it works just fine! Thank you for finding this and fixing the problem!

**Comment by SabineHaas** [comment]
Thanks @MaGering for adapting the last csvs!

@Piranias can we already merge this PR? have you tested it? 

I haven't done the github release, yet, due to this open PR.

**Comment by Piranias** [comment]
> Thanks @MaGering for adapting the last csvs!
> 
> @Piranias can we already merge this PR? have you tested it?
> 
> I haven't done the github release, yet, due to this open PR.

yes, it works just fine

**Pull request merged**
