### PR TITLE
Update demand documentation

### LINKED ISSUE #40: [docs] links in code documentation need to be fixed
In the[ code documentation on readthedocs](https://pvcompare.readthedocs.io/en/latest/code.html) the links (and explanatory sentence) of the module `demand` does not work.
Probably the docstrings need to be adapted.

### PR DESCRIPTION
**Pull request by SabineHaas**
**Changes proposed in this pull request**:
- Update docstrings of `demand` module

The following steps were realized, as well (if applies):
- :x: Use in-line comments to explain your code
- :x: Write docstrings to your code
- :x: For new functionalities: Explain in readthedocs
- :x: Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [x] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by SabineHaas** [comment]
This is strange.. the check of `black` is failing. However, in my local repository all is fine. Before applying reformatting with `black`, however, the checks passed. 
I even fixed the version number in `test_requirements.txt` to be sure locally and remote it's the same version.

Could you try in your local repository @Piranias ?

**Comment by Piranias** [comment]
> This is strange.. the check of `black` is failing. However, in my local repository all is fine. Before applying reformatting with `black`, however, the checks passed.
> I even fixed the version number in `test_requirements.txt` to be sure locally and remote it's the same version.
> 
> Could you try in your local repository @Piranias ?

strange, you must have a different blacks on your computer ;)
I applied blacks again and all test files were reformatted. At least the tests seem to work now :)

**Comment by SabineHaas** [comment]
> > This is strange.. the check of `black` is failing. However, in my local repository all is fine. Before applying reformatting with `black`, however, the checks passed.
> > I even fixed the version number in `test_requirements.txt` to be sure locally and remote it's the same version.
> > Could you try in your local repository @Piranias ?
> 
> strange, you must have a different blacks on your computer ;)
> I applied blacks again and all test files were reformatted. At least the checks seem to work now :)

:D Okay, I'm glad, that it's like that and not a bigger problem. Still it's weird because I added my version to the requirements (`19.10b0`) Which version of black are you using?

**Comment by Piranias** [comment]
> :D Okay, I'm glad, that it's like that and not a bigger problem. Still it's weird because I added my version to the requirements (`19.10b0`) Which version of black are you using?

same:
 black (19.10b0)

**Pull request merged**
