### PR TITLE
Feature/update pvcompare packages

### LINKED ISSUE #57: Install MVS as pypi package (once it is released on pypi)
I will discuss about that with @Bachibouzouk

connected to MVS issue https://github.com/rl-institut/mvs_eland/issues/423

### PR DESCRIPTION
**Pull request by SabineHaas**
Fix #57

**Changes proposed in this pull request**:
- Add all packages to setup.py and remove requirements.txt 
- Update pvcompare to the latest MVS version

The following steps were realized, as well (if applies):
:x:  Use in-line comments to explain your code
:x:  Write docstrings to your code
:x:  For new functionalities: Explain in readthedocs
:x:  Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [x] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by SabineHaas** [comment]
@Piranias Do you need 
[these dependencies](https://github.com/greco-project/greco_technologies/blob/3f1530444b9b4c8650a4ab69f24bf5a314dcb091/setup.py#L31-L32) to be the exact version you specified?

I get the following warnings when installing pvcompare:
```
greco-technologies 0.0.1 requires feedinlib==0.0.12, but you'll have feedinlib 0.1.0rc2 which is incompatible.
greco-technologies 0.0.1 requires xarray==0.15.0, but you'll have xarray 0.16.1 which is incompatible.
```
I think  feedinlib 0.1.0rc2  is needed for era5 data, I think xarray is used in feedinlib, as well.

**Comment by SabineHaas** [comment]
`error: Could not find suitable distribution for Requirement.parse('mvs_eland[report]@ git+https://github.com/rl-institut/mvs_eland.git@v0.4.0')` 

Strangely this works locally but not on travis. As we will have a solution on that with #42 I won't fix this. 

Let's wait before we merge

**Comment by Piranias** [comment]
> @Piranias Do you need
> [these dependencies](https://github.com/greco-project/greco_technologies/blob/3f1530444b9b4c8650a4ab69f24bf5a314dcb091/setup.py#L31-L32) to be the exact version you specified?
> 
> I get the following warnings when installing pvcompare:
> 
> ```
> greco-technologies 0.0.1 requires feedinlib==0.0.12, but you'll have feedinlib 0.1.0rc2 which is incompatible.
> greco-technologies 0.0.1 requires xarray==0.15.0, but you'll have xarray 0.16.1 which is incompatible.
> ```
> 
> I think feedinlib 0.1.0rc2 is needed for era5 data, I think xarray is used in feedinlib, as well.

Did you solve this? To be honest I'm not sure is these exact versions are needed. I guess you could change them and see if there's conflicts

**Comment by SabineHaas** [comment]
> > @Piranias Do you need
> > [these dependencies](https://github.com/greco-project/greco_technologies/blob/3f1530444b9b4c8650a4ab69f24bf5a314dcb091/setup.py#L31-L32) to be the exact version you specified?
> > I get the following warnings when installing pvcompare:
> > ```
> > greco-technologies 0.0.1 requires feedinlib==0.0.12, but you'll have feedinlib 0.1.0rc2 which is incompatible.
> > greco-technologies 0.0.1 requires xarray==0.15.0, but you'll have xarray 0.16.1 which is incompatible.
> > ```
> > 
> > 
> > I think feedinlib 0.1.0rc2 is needed for era5 data, I think xarray is used in feedinlib, as well.
> 
> Did you solve this? To be honest I'm not sure is these exact versions are needed. I guess you could change them and see if there's conflicts

No I wanted to wait what you say, whether there was a reason for the limitations.

**Comment by SabineHaas** [comment]
> > > @Piranias Do you need
> > > [these dependencies](https://github.com/greco-project/greco_technologies/blob/3f1530444b9b4c8650a4ab69f24bf5a314dcb091/setup.py#L31-L32) to be the exact version you specified?
> > > I get the following warnings when installing pvcompare:
> > > ```
> > > greco-technologies 0.0.1 requires feedinlib==0.0.12, but you'll have feedinlib 0.1.0rc2 which is incompatible.
> > > greco-technologies 0.0.1 requires xarray==0.15.0, but you'll have xarray 0.16.1 which is incompatible.
> > > ```
> > > 
> > > 
> > > I think feedinlib 0.1.0rc2 is needed for era5 data, I think xarray is used in feedinlib, as well.
> > 
> > 
> > Did you solve this? To be honest I'm not sure is these exact versions are needed. I guess you could change them and see if there's conflicts
> 
> No I wanted to wait what you say, whether there was a reason for the limitations.

I made a PR in greco_technologies https://github.com/greco-project/greco_technologies/pull/2

**Comment by SabineHaas** [comment]
ready to review :)

**Review by Piranias — APPROVED** [review]

**Pull request merged**
