### PR TITLE
Update mvs inputs of sector coupling to data in user input collection

### PR DESCRIPTION
**Pull request by MaGering**
With this PR the mvs inputs data of the sector-coupling example is updated to the values stored in user's inputs collection, since it was outdated.

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by MaGering** [comment]
@SabineHaas, @Piranias, whoever has time for a review. It's no big deal though. :)
The corrections relate to overall parameters such as the currency or PV plant parameters and not heat specific parameters such as the heat pump's.

**Review by Piranias — APPROVED** [review]
did you also check the same values in the other template (electricity sector) and the mvs inputs collection folder?

**Comment by MaGering** [comment]
> did you also check the same values in the other template (electricity sector) and the mvs inputs collection folder?

Well I adapted the values to the ones in the mvs user inputs collection. They are up to date, aren't they? I have seen that the inputs of the electricity sector match those of the user inputs collection (on random checks). However, I have not checked all the values. Now however, I noticed that the lifetime of the solar inverter in the electricity sector example does not match the one in the user inputs collection. Would you like to correct that in this PR and maybe check the other values as well? For me it is a bit difficult to say which parameter is the correct one, since we don't have the comments in the user inputs collection any more.

**Comment by Piranias** [comment]
> > did you also check the same values in the other template (electricity sector) and the mvs inputs collection folder?
> 
> Well I adapted the values to the ones in the mvs user inputs collection. They are up to date, aren't they? I have seen that the inputs of the electricity sector match those of the user inputs collection (on random checks). However, I have not checked all the values. Now however, I noticed that the lifetime of the solar inverter in the electricity sector example does not match the one in the user inputs collection. Would you like to correct that in this PR and maybe check the other values as well? For me it is a bit difficult to say which parameter is the correct one, since we don't have the comments in the user inputs collection any more.



> > did you also check the same values in the other template (electricity sector) and the mvs inputs collection folder?
> 
> Well I adapted the values to the ones in the mvs user inputs collection. They are up to date, aren't they? I have seen that the inputs of the electricity sector match those of the user inputs collection (on random checks). However, I have not checked all the values. Now however, I noticed that the lifetime of the solar inverter in the electricity sector example does not match the one in the user inputs collection. Would you like to correct that in this PR and maybe check the other values as well? For me it is a bit difficult to say which parameter is the correct one, since we don't have the comments in the user inputs collection any more.

ok, i can do another review of all parameters (except hp parameters) in another PR

**Comment by MaGering** [comment]
> ok, i can do another review of all parameters (except hp parameters) in another PR

Thanks, that would be great! 😃 So I merge this PR, right?

**Pull request merged**
